### ISSUE TITLE
Icons are enormous with Obsidian 0.14.4

### ISSUE THREAD

**Issue by I-Pch** [aidenlx/obsidian-icon-shortcodes#43]
I think Obsidian is breaking Icons Shortcodes 😓 ...

Just updated to the latest insider release (Obsidian `0.14.4`) and now icons in a note are looking like this 😔 ...
(whatever view I'm in)

<img width="1440" alt="Icons short" src="https://user-images.githubusercontent.com/77828085/161097323-29f0d220-0ac0-41e9-924c-0a6968c5a7ff.png">

**Comment by I-Pch** [comment]
While waiting for this to be fixed at the source 😊 and because I really couldn't use Obsidian with icons as big as the readable length of my notes, I found a temporary solution by modifying the `style.css` from the plugin directly (I tried to use a snippet as suggested in the README instead but couldn't make it work 🤷‍♀️ ) 

So the bug seems to lie somewhere in this part of the `style.css` (as the `--editor-font` has been replaced by `--font-text`) : 

```css
[...]

.markdown-preview-view .isc-icon>img,
.markdown-preview-view .isc-icon>svg,
.markdown-source-view .isc-icon>img,
.markdown-source-view .isc-icon>svg {
  height: var(--editor-font-size);
  width: var(--editor-font-size)
}

[...]
```

By just changing the `var(--editor-font-size)` by `var(--font-text-size)` for the `height` and `width` I was able to get back workable sized icons 😊 ...
