### ISSUE TITLE
Icons oversized in headers

### ISSUE THREAD

**Issue by zambony** [aidenlx/obsidian-icon-shortcodes#63]
Icons inserted into a header are oversized. Emojis are fine.

![image](https://user-images.githubusercontent.com/3318117/207681758-837f3f94-1898-4314-b31f-f28e45fff6c2.png)

Temporarily fixed with a snippet:

```css
.isc-icon.isc-svg-icon {
    height: 1em;
    width: 1em;
    vertical-align: middle;
}

.isc-icon.isc-svg-icon > svg {
    max-width: 1em;
    max-height: 1em;
}
```

![image](https://user-images.githubusercontent.com/3318117/207682471-4ee16454-e8c4-4481-91e0-75dd124890d5.png)

**Comment by jessicarod7** [comment]
Seems to be a recurrence of #59, Obsidian changed the meaning of the `--h#-size` variable, but I'm not sure what to. Anyways, I modified @p-laranjinha's [script](https://github.com/aidenlx/obsidian-icon-shortcodes/issues/59#issuecomment-1279180633) from the previous issue, and this seems to work in v1.3.4:

```css
.markdown-source-view .HyperMD-header-1 .isc-icon>img,
.markdown-source-view .HyperMD-header-1 .isc-icon>svg,
.markdown-preview-view h1 .isc-icon>img,
.markdown-preview-view h1 .isc-icon>svg {
    height: calc(var(--h1-line-height) * 1em); /* --h#-line-height is unitless */
    width: calc(var(--h1-line-height) * 1em);
}

.markdown-source-view .HyperMD-header-2 .isc-icon>img,
.markdown-source-view .HyperMD-header-2 .isc-icon>svg,
.markdown-preview-view h2 .isc-icon>img,
.markdown-preview-view h2 .isc-icon>svg {
    height: calc(var(--h2-line-height) * 1em);
    width: calc(var(--h2-line-height) * 1em);
}

.markdown-source-view .HyperMD-header-3 .isc-icon>img,
.markdown-source-view .HyperMD-header-3 .isc-icon>svg,
.markdown-preview-view h3 .isc-icon>img,
.markdown-preview-view h3 .isc-icon>svg {
    height: calc(var(--h3-line-height) * 1em);
    width: calc(var(--h3-line-height) * 1em);
}

.markdown-source-view .HyperMD-header-4 .isc-icon>img,
.markdown-source-view .HyperMD-header-4 .isc-icon>svg,
.markdown-preview-view h4 .isc-icon>img,
.markdown-preview-view h4 .isc-icon>svg {
    height: calc(var(--h4-line-height) * 1em);
    width: calc(var(--h4-line-height) * 1em);
}

.markdown-source-view .HyperMD-header-5 .isc-icon>img,
.markdown-source-view .HyperMD-header-5 .isc-icon>svg,
.markdown-preview-view h5 .isc-icon>img,
.markdown-preview-view h5 .isc-icon>svg {
    height: calc(var(--h5-line-height) * 1em);
    width: calc(var(--h5-line-height) * 1em);
}

.markdown-source-view .HyperMD-header-6 .isc-icon>img,
.markdown-source-view .HyperMD-header-6 .isc-icon>svg,
.markdown-preview-view h6 .isc-icon>img,
.markdown-preview-view h6 .isc-icon>svg {
    height: calc(var(--h6-line-height) * 1em);
    width: calc(var(--h6-line-height) * 1em);
}
```
